### ISSUE TITLE
Display version number

### ISSUE THREAD

**Issue by gottsman** [sibson/vncdotool#100]
Can a "--version" flag or something similar be implemented? Struggling with some compatibility issues between current (0.11.1) and 0.10.0 for some reason.

Being able to display the version would help with debugging.

**Comment by gottsman** [comment]
Figured out the issue between versions.... DesktopSize Pseudo-Encoding defaults changed... 

`vncdotool --version`

would be nice.

**Comment by sibson** [comment]
fixed by #107
