### ISSUE TITLE
Unable to connect using 0.11.2, while using 0.10.0 works fine.

### ISSUE THREAD

**Issue by HeavyThumper** [sibson/vncdotool#102]
I've been using 0.10.0 for a year - working quite well though I'd like to start using the features I'm seeing in 0.11.x.  I just upgraded...and broke!  After testing, it seems like it's not dependency related - I tried downgrading twisted, zope, pillow - that didn't fix it.  Using the current versions of the dependencies but 0.10.0 I'm able to connect and function again.

My test run:
(venv-vncdotool) root@daisy:/opt/venv-vncdotool# pip install -U vncdotool
Collecting vncdotool
Requirement already up-to-date: Pillow in ./lib/python2.7/site-packages (from vncdotool)
Requirement already up-to-date: Twisted in ./lib/python2.7/site-packages (from vncdotool)
Requirement already up-to-date: olefile in ./lib/python2.7/site-packages (from Pillow->vncdotool)
Requirement already up-to-date: Automat>=0.3.0 in ./lib/python2.7/site-packages (from Twisted->vncdotool)
Requirement already up-to-date: zope.interface>=3.6.0 in ./lib/python2.7/site-packages (from Twisted->vncdotool)
Requirement already up-to-date: constantly>=15.1 in ./lib/python2.7/site-packages (from Twisted->vncdotool)
Requirement already up-to-date: hyperlink>=17.1.1 in ./lib/python2.7/site-packages (from Twisted->vncdotool)
Requirement already up-to-date: incremental>=16.10.1 in ./lib/python2.7/site-packages (from Twisted->vncdotool)
Requirement already up-to-date: six in ./lib/python2.7/site-packages (from Automat>=0.3.0->Twisted->vncdotool)
Requirement already up-to-date: attrs in ./lib/python2.7/site-packages (from Automat>=0.3.0->Twisted->vncdotool)
Requirement already up-to-date: setuptools in ./lib/python2.7/site-packages (from zope.interface>=3.6.0->Twisted->vncdotool)
Installing collected packages: vncdotool
  Found existing installation: vncdotool 0.10.0
    Uninstalling vncdotool-0.10.0:
      Successfully uninstalled vncdotool-0.10.0
Successfully installed vncdotool-0.11.2
(venv-vncdotool) root@daisy:/opt/venv-vncdotool# vncdo -v -v --delay=500 -s xxx::xxx -p ppp key esc
INFO:root:connecting to xxx:xxx
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory instance at 0x7f22db652d88>
INFO:twisted:Using protocol version 3.300
INFO:twisted:Cannot connect authentication failed
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory instance at 0x7f22db652d88>
INFO:twisted:Main loop terminated.
(venv-vncdotool) root@daisy:/opt/venv-vncdotool# pip install vncdotool==0.10.0
Collecting vncdotool==0.10.0
Requirement already satisfied: Pillow in ./lib/python2.7/site-packages (from vncdotool==0.10.0)
Requirement already satisfied: Twisted in ./lib/python2.7/site-packages (from vncdotool==0.10.0)
Requirement already satisfied: olefile in ./lib/python2.7/site-packages (from Pillow->vncdotool==0.10.0)
Requirement already satisfied: Automat>=0.3.0 in ./lib/python2.7/site-packages (from Twisted->vncdotool==0.10.0)
Requirement already satisfied: zope.interface>=3.6.0 in ./lib/python2.7/site-packages (from Twisted->vncdotool==0.10.0)
Requirement already satisfied: constantly>=15.1 in ./lib/python2.7/site-packages (from Twisted->vncdotool==0.10.0)
Requirement already satisfied: hyperlink>=17.1.1 in ./lib/python2.7/site-packages (from Twisted->vncdotool==0.10.0)
Requirement already satisfied: incremental>=16.10.1 in ./lib/python2.7/site-packages (from Twisted->vncdotool==0.10.0)
Requirement already satisfied: six in ./lib/python2.7/site-packages (from Automat>=0.3.0->Twisted->vncdotool==0.10.0)
Requirement already satisfied: attrs in ./lib/python2.7/site-packages (from Automat>=0.3.0->Twisted->vncdotool==0.10.0)
Requirement already satisfied: setuptools in ./lib/python2.7/site-packages (from zope.interface>=3.6.0->Twisted->vncdotool==0.10.0)
Installing collected packages: vncdotool
  Found existing installation: vncdotool 0.11.2
    Uninstalling vncdotool-0.11.2:
      Successfully uninstalled vncdotool-0.11.2
Successfully installed vncdotool-0.10.0
(venv-vncdotool) root@daisy:/opt/venv-vncdotool# vncdo -v -v --delay=500 -s xxx::xxx -p ppp key esc
INFO:root:connecting to xxx:xxx
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory instance at 0x7f5eefbd1680>
INFO:twisted:Using protocol version 3.300
INFO:root:connected to user's user desktop (server:3)
DEBUG:vncdotool.client:keyPress esc
DEBUG:vncdotool.client:keyDown esc
DEBUG:vncdotool.client:keyUp esc
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory instance at 0x7f5eefbd1680>
INFO:twisted:Main loop terminated.

**Comment by gottsman** [comment]
I had issues with this as well... For me, I connect to local androids on wifi only for my farm. I ended up clearing the password (set to blank) and its happy now.

**Comment by sibson** [comment]
This could have been fixed by #105, would be appreciated if anyone can confirm if master is working for them.

**Comment by sibson** [comment]
I'm going to assume this has been fixed, if not please re-open.
