### ISSUE TITLE
vnclog not logging

### ISSUE THREAD

**Issue by KuduDodge** [sibson/vncdotool#106]
I can't make vnclog emit logfiles or output. I've only tried the 0.11.2 tag (via pip) and the current head of master.

Process:
* start with updated ubuntu 16.04 desktop
* sudo apt-get install -y python-pip xvnc4viewer
* sudo pip download vncdotool (to get all the dependencies)
* sudo pip install $( ls | grep -v vncdotool ) virtualenv
* git clone https://github.com/sibson/vncdotool
* VNC Server: Ubuntu 14.04 running vnc4server-4.1.1+xorg4.3.0-37ubuntu5.0.2, lau
nched using "vncserver". Server has fluxbox installed. Configured -AlwaysShared
* Validated "vncdo" works.
* python debian/vnclog -s <IP>:1 --logfile=vnclog.log vnclog.out
* xvnc4viewer localhost:2
* Password prompt, enter password
* [ do things ]
* exit xvnc4viewer
* Look at vnclog.log and vnclog.out, they are 0 bytes long
* Hit ^C in vnclog
* Look at vnclog.log and vnclog.out, they are 0 bytes long
* also tried xvnc4viewer -PreferredEncoding=raw localhost:2

I've tried to grok what's going on in loggingproxy.py, but I'm failing. By adding print statements I see lots of activity handled by VNCLoggingServerProxy._handle_security, but nothing seems to lead to handle_keyEvent or handle_pointerEvent.

**Comment by sibson** [comment]
I'm guessing you are hitting a yet to be implemented path, either https://github.com/sibson/vncdotool/blob/master/vncdotool/loggingproxy.py#L57 or https://github.com/sibson/vncdotool/blob/master/vncdotool/loggingproxy.py#L71.   I recall struggling to make password's work properly, so it could be that path still needs to be fleshed out.

**Comment by sibeshkar** [comment]
Thanks for this tool! Any progress fixing vnclog? As far as I see, there is no way to capture keystrokes and point events in a .vd script?
