### ISSUE TITLE
Feature Request: Timeout functionality in API

### ISSUE THREAD

**Issue by gottsman** [sibson/vncdotool#108]
As described in the title, looking to start a thread on add a timeout feature to the API. Its available on the CLI, but the API would be nice as well.

**Comment by sibson** [comment]
some ideas are in https://github.com/sibson/vncdotool/issues/70#issuecomment-344780105

**Comment by gottsman** [comment]
Confirming that the script has worked wonders in my script. Thank you @noxdafox for the patch.

**Comment by noxdafox** [comment]
Np, glad it helped!
