### ISSUE TITLE
Replace Twisted with asyncio

### ISSUE THREAD

**Issue by sibson** [sibson/vncdotool#114]
@noxdafox says "have you considered switching to asyncio in favor of Twisted at least on Python > 3.5?"

https://github.com/sibson/vncdotool/pull/111#discussion_r157795960

**Comment by sibson** [comment]
I've not considered it. What would be the benefit?

**Comment by noxdafox** [comment]
1. Removal of fairly large external dependency (> 15 Mb) in favour of a Python standard library module
2. A better documented and supported IO library
3. `asyncio` seems to be the module Python community is pushing forward for IO based solutions
4. vncdotool could be better integrated with `asyncio` based frameworks (example `aiohttp`)

The latter is marginal as AFAIK Twisted is `asyncio` compatible as well.

**Comment by sibson** [comment]
It sounds like the main argument you are making is that asyncio is the way for the future and would be easier to develop against. I see vncdotool as mostly feature complete, at least as far as the core functionality goes.  Thus, I'm not sure there would be much return on investment from porting it.  We'd also need to consider if a port would be backwards compatible or not.
