### ISSUE TITLE
Protocol version 3.889 not supported

### ISSUE THREAD

**Issue by xiewenwei** [sibson/vncdotool#115]
INFO:root:connecting to boohee-jk:5900
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory instance at 0x7fb7e5ccb098>
INFO:twisted:Protocol version 3.889 not supported
INFO:twisted:Using protocol version 3.300
INFO:twisted:Connection refused: 'Incompatible Version.'
INFO:twisted:Stopping factory <vncdotool.command.VNCDoCLIFactory instance at 0x7fb7e5ccb098>
INFO:twisted:Main loop terminated.

My vnc server is builtin of mac OSX Version 10.12 Sierra.

**Comment by agfor** [comment]
@xiewenwei Have you tried again with the latest master? It supports versions 3.3, 3.7, and 3.8 (as of today). It should attempt to use version 3.8 if your server sends version 3.889.

**Comment by agfor** [comment]
@xiewenwei Also, I have a patch that makes this tool work around other problems with the OSX built-in server that I plan to PR shortly.

**Comment by sibson** [comment]
#126 has been merged, I'm assuming that resolves this too.  Please re-open if that isn't the case.  t
