### ISSUE TITLE
Support for multiple resolutions

### ISSUE THREAD

**Issue by mpaf** [sibson/vncdotool#12]
HI! I'm happy to have found your project, it's indeed a great thing. Simple and good implementation of recording and playback of vnc commands, I like the extra features like adding an extra delay between actions. Nice stuff!

I was wondering, are you considering to implement screen-resolution independent playback? Say I have a recorded sequence of actions which I want to playback across different machines which I'm administering but these have different resolutions. I guess you would need to detect resolution and transform coordinate system of RBF actions accordingly. Is such thing in the works for you guys?

Thanks for your good work

**Comment by sibson** [comment]
I think the best way to handle this is write an external script that can rewrite .vdo files.  So you would could something like

    cat myscript.vdo | rescaler.py --native 1900x1080 --target 800x600 | vncdo -s server.example.com

Of course, you could make a smarter command that doesn't require the pipes but that would be less illustrative of the idea.
