### ISSUE TITLE
'enter' key or move with click doesn't work

### ISSUE THREAD

**Issue by jaswinder-saini** [sibson/vncdotool#131]
I have the following configurations:
 - [ vnc4server  4.1.1+xorg4.3.0-37ubuntu5.0.2 ] VNC server and version
   other vncservers installed on my system:
     -->  xtightvncviewer 1.3.9-6.4ubuntu1
     --> remmina-plugin-vnc  1.0.0-4ubuntu3
 - [ 0.12.0 ] vncdotool version
 - Run a python script consisting vncdo commands as 

`sudo python3 py-scripts/automation.py xxx.xxx.xx.xxx  password testuser testpass`

for script:

  `#!/usr/bin/python

import sys
import os

saddress = sys.argv[1]
spassword =  sys.argv[2]
susername =  sys.argv[3]
spasw = sys.argv[4]

os.system('vncserver -kill :1')
os.system('sudo vncdo -v -s  ' + saddress + ' -p ' + spassword + ' --delay=1500 ' + 
	      ' type ' + susername + 
	      ' key tab type ' + spasw + 
              ' move 1045 525 click 1 click 2 click 3 key enter key enter pause 60 capture mousepointer.jpg '
          )
os.system('vncserver -kill :1')`

In the above script, I tried to login on a Mac 10.x but even after providing enter key or click event on submit button,It still stuck there.

**Comment by pmhahn** [comment]
version `0.12.0` is too old; please give the version in git branch `main` a try as it supports macOS since #200:
> pip install git+https://github.com/sibson/vncdotool.git@main

If this still does not work feel free to re-open this issue or to file a new issue.
