### ISSUE TITLE
vncdotool doesn't work when user logged in MacOS.

### ISSUE THREAD

**Issue by tomasrinta116** [sibson/vncdotool#133]
I connected to my server(MacOS X, 10.13 HighSierra) with VNCViwer.
I can control my server with VNCViewer, type texts, open a finder etc.
But with vncdotool, I can log in (in this case, not logged in), it means I can do type texts with vncdotool.
But after logged in, I can not do anything with vncdotool even VNCViwer works.
Please help me with this issue.

 Have you included the following information?

 - [ 6.3.1 ] VNC server and version
 - [ 0.10.0, 0.12.0 ] vncdotool version
 - [ ] steps to reproduce

**Comment by egandro** [comment]
$ sudo -S kill -9 $(ps -ef | grep "loginwindow" | awk '{print $2}' | head -n1)

**Comment by pmhahn** [comment]
> [ 0.10.0, 0.12.0 ] vncdotool version

is too old and does not have support for _DH Authentication_ ,which is required for _Apple Remote Desktop_ (ARD). It only got added via #200 after version `v1.0.0` and is only available from the current development branch:
```sh
pip install git+https://github.com/sibson/vncdotool.git@main
```

Despite not having macOS myself I'm going to close this issue for now. If you still experience the problem feel free to re-open this issue or to create a new one.
