### ISSUE TITLE
(r)expect does not check the current screen

### ISSUE THREAD

**Issue by tghosgor** [sibson/vncdotool#141]
`expect` and `rexpect` commands fail to match if the current screen matches the provided image.

 - VNC Server: VNC server of QEMU emulator version 3.1.0
 - vncdotool 0.12.1

1. Start the QEMU instance, let it boot until you get the screen that you will "expect".
2. Do an "expect" operation, VNC hangs forever.
3. Switch to another terminal (possibly with different image) and switch back,
4. "expect" now matches.

If I switch [incremental to 0 on client.py](https://github.com/sibson/vncdotool/blob/d308133ee66a95c849f2d9b05faeeb87fc120561/vncdotool/client.py#L281), then "expect" matches the current screen as expected.

**Comment by luke-jr** [comment]
Changing incremental=0 on that line did NOT fix the issue for me, FWIW

**Comment by pmhahn** [comment]
As `incremental=False` is the default and it works for me, I'm closing this issue:
```sh
vncdo -s localhost::5900 capture screen.png
vncdo -s localhost::5900 expect screen.png 1
```

You might want to give the version from git branch `main` a try:
> pip install git+https://github.com/sibson/vncdotool.git@main

You you still experience the problem feel free to re-open this issue or to file a new one.

> Changing incremental=0 on that line did NOT fix the issue for me, FWIW

Is 'rexpect' the only command you run or is this part of a larger sequence? There's a known issue where `vncdo` might hang if the screen is not changed as then no _update rectangles_ will be send and `vncdo` has no chance to detect that.
