### ISSUE TITLE
vnclog not w

### ISSUE THREAD

**Issue by datahunter88** [sibson/vncdotool#154]
Have you included the following information?

 - [] VNC server and version
qemu-2.8

 - [] vncdotool version
0.12.1 (install by pip)

 - [ ] steps to reproduce

Run below command in bash shell
1. vnclog -v -s localhost::5900 keylog.vdo
2. use UltraVNC connect to 5902 port and do something

The keylog.vdo without content
The vnlog keep in loop without termination

log
INFO:twisted:VNCLoggingServerFactory starting on 5902
INFO:twisted:Starting factory <vncdotool.loggingproxy.VNCLoggingServerFactory instance at 0x7fe6796e7830>
INFO:proxy:new connection from 192.168.88.177
INFO:twisted:Starting factory <vncdotool.loggingproxy.VNCLoggingClientFactory instance at 0x7fe6796ecab8>
INFO:twisted:Stopping factory <vncdotool.loggingproxy.VNCLoggingClientFactory instance at 0x7fe6796ecab8>

**Comment by Paulynz** [comment]
Any fix for this one?

**Comment by Paulynz** [comment]
@sibson good day sir, would like to ask if why vnclog won't record logs. still 0 bytes. after running above command.
![image](https://user-images.githubusercontent.com/42842792/97101642-196a2380-16da-11eb-826a-7ba89a8d4204.png)

**Comment by pmhahn** [comment]
Probably a duplicate of issue #140

**Comment by sibson** [comment]
yup, seems like a dup
