### ISSUE TITLE
Is touch supported?

### ISSUE THREAD

**Issue by TylerGubala** [sibson/vncdotool#155]
Is it possible to send touch commands to the VNC server using this library?

I have a use-case where touch would be very useful. All I see are mouse commands though. 

I'm pretty sure that VNC supports touch, although I am not speaking from experience, just from things I have read online.

**Comment by sibson** [comment]
There is no support today. If the VNC protocol extension is documented, I'd imagine it's fairly straightforward to add.

**Comment by TylerGubala** [comment]
Actually doing a lot of further reading I think I confused using touch client side to position the cursor on the server with actual multitouch support, although I think RDP does support touch, but that is a different protocol so I'll just close the issue I guess.
