### ISSUE TITLE
Install on PyCharm CE on macOS Catalina hangs forever

### ISSUE THREAD

**Issue by Sposito** [sibson/vncdotool#171]
- [ ] vncdotool version

- tried 1.0.0 and 0.13.0

 - [ ] steps to reproduce
- create a new project
- set the environment to a venv with latest python version
- try to install the package
- it will hang forever

**Comment by sibson** [comment]
There aren't enough details here for me to debug and it seems like an environment issue rather than a direct problem with vncdotool.
