### ISSUE TITLE
Pyclick instead of vncdotool's mouse

### ISSUE THREAD

**Issue by nubonics** [sibson/vncdotool#173]
Feature Request
- Use pyclick instead of vncdotool's mouse

Also, If I wanted to expedite or implement this myself, how would I go about doing so?

**Comment by sibson** [comment]
I'm not familiar with pyclick, but if the movement planning is sufficiently abstracted it seems like a reasonable thing to consider.  My only hesitation would be what do we gain from using pyclick? While the current implementation is naive, what are the downsides of such direct movement?  Additionally, does adding a new dependency potentially create installation issues for some users?  If you wanted to implement yourself, I'd be happy to look at a PR.

**Comment by nubonics** [comment]
The purpose of doing this is to counter detection methods, creating bots / automation, which is my goal, so if you do not support doing so I understand. 

Also, (on the same topic of botting / automation) another thing to consider is upgrading from PIL to mss, as this significantly increases the FPS (if the frames were to go somewhere besides a screenshot, or a vnc client) I've done a small scale test with PIL vs mss when using / modifying sentdex's GTAV client (ml/ai learning to drive in the gtav environment). I switched to mss and got far better results (double if i recall, but I wouldn't quote me on this). I do believe others could benefit from this implementation, I just don't know about frame-buffers and the required things to achieve this.

I'm not looking to send a PR, more-so of learning how vncdotool is using the mouse. I see that twisted is being used, and that their are custom made functions for the mouseDown, mouseUp, mouseMove and click, however, I tried to implement pyclick myself, and failed, not to worry. I will try again soon, and if not find support to do so.

**Comment by sibson** [comment]
I'm open to improving the mouseMove algo, or making it configurable.  As I don't have a need to do so I won't be implementing it.  If you don't intend to send a PR then I don't see value in keeping this issue open and will be closing it unless there is reason not to.
