### ISSUE TITLE
Feature request: capture without saving to disk

### ISSUE THREAD

**Issue by nubonics** [sibson/vncdotool#174]
**:Feature request:**
**Purpose**: Allows a user to add their own custom object detection, or perhaps be able to create their own client by just using the image(s) that are gathered from the capture

Hi, I would like to use vncdotool to capture the screen and not save to the disk, so that I can apply my own object detection, instead of using `expect`

**Comment by nubonics** [comment]
Did find another way, as `mss` allows a display option to be used

**Comment by sibson** [comment]
It sounds like you don't need this feature, as such I'm closing.
