### ISSUE TITLE
vncdotools Python version 3 issue

### ISSUE THREAD

**Issue by yogeshcsdev** [sibson/vncdotool#179]
Hi,
I'm using this documentation for installation. https://vncdotool.readthedocs.io/en/latest/install.html
As it says to use Python version 2, I'm following that and everything is working fine. But Python version 2 us deprecating soon. How can I make vncdotools work with Python version 3?

I have also tried installation under Python version 3, it did not work, either installation fails or below command errors out
`vncdo.exe --server som.eip.add.res type "Hello World"`

 - **VNC server and version**: Tight VNC 2.8.27
 - **vncdotool version**: 1.0.0
 - **steps to reproduce**: follow all steps given in https://vncdotool.readthedocs.io/en/latest/install.html , just use Python version 3.8.2.

**Comment by sibson** [comment]
Py3k should be working find now.
