### ISSUE TITLE
Question: vncdotool api hangs on method independent of RealVNC server authentication, is there a way to trouble shoot this behavior?

### ISSUE THREAD

**Issue by carmelotony** [sibson/vncdotool#187]
- [ ] RealVNC 
 - [ ] vncdotool current PIP version

Is there a way to pass authentication credentials (User: Password:)?

**Comment by carmelotony** [comment]
Changing to different authentication modes in RealVNC did not resolve the hanging issue. I have confirmed raw encoding. Is there anything else I should be checking? I don't get an error traceback, the application just hangs in both the api and command line connections.

**Comment by dozysun** [comment]
If you auth passwd is wrong, the process will hang up, see [https://github.com/sibson/vncdotool/pull/189](url), I have sent a merge request to fix it

**Comment by nmz787** [comment]
same thing happening here with this server `VNC(R) Server 6.4.1 (r40826) x64 (Mar 13 2019 16:31:16)`

**Comment by sibson** [comment]
#189 is merged, assuming that fixes this issue.  Please re-open if not.
