### ISSUE TITLE
vncdotool  use error,  need upgrade dependencies

### ISSUE THREAD

**Issue by dozysun** [sibson/vncdotool#190]
- [ ] VNC server and version: docker address: https://hub.docker.com/r/vncserver/lubuntu
 - [ ] vncdotool version: vncdotool 1.0.0
 python version: 3.9.5

when do   'vncdo -s xxxx:5901 type --password=xxx type "hello world"'
will cause  "builtins.TypeError: unsupported operand type(s) for &: 'str' and 'int'. CRITICAL:root:unsupported operand type(s) for &: 'str' and 'int'"

upgrade Pillow==8.2.0  and zope.interface==5.4.0 fix it

**Comment by SebJansen** [comment]
@dozysun your fix did not work for me
I am using Pillow==8.3.1 and zope.interface==5.4.0, yet I get error `unsupported operand type(s) for &: 'str' and 'int'`

downgrading to vncdotool v0.13 fixed it for me

**Comment by pmhahn** [comment]
There have been many fixed to the git `main` branch, which dropped Python 2 support and fixed many `bytes` / `unicode` issues along the way. My tests yesterday showed that it now works.

You can try the latest development version yourself:
```sh
pip install git+https://github.com/sibson/vncdotool.git@main
```
