### ISSUE TITLE
[BUG] version inconsistency

### ISSUE THREAD

**Issue by Kochise** [sibson/vncdotool#203]
Latest release is `0.12.0` (april 7th 2018) : https://github.com/sibson/vncdotool/releases
Pypi release is `1.0.0` (april 11th 2020) : https://pypi.org/project/vncdotool/
Current version is still `1.0.0` (april 11th 2020) : https://github.com/sibson/vncdotool/blob/main/vncdotool/__init__.py

Despite all the changes : https://github.com/sibson/vncdotool/commits/main

**Comment by guicho271828** [comment]
yes due to this I always have to pull git+https:// address

**Comment by sibson** [comment]
I've started preparing a 1.1.0 release with updated dependencies, once I get some confirmation that everything works I'll cut a new release.

**Comment by pmhahn** [comment]
# Already merged
- feat: Add support for Apple Remote Desktop (ARD)
- refactor: Drop support for Python 2 and up to Python 3.6
- fix: Improve unchanged framebuffer comparison
- test: Switch to `unittest` for testing
- test: Add several new tests to unit test suite
- test: Add functional test suite
- churn: Update dependencies for `pillow`, `twisted`, `pycryptodome`
- style: Add PEP-484 type hinting
- refactor: Improve code style and convert to more modern Python style
- doc: Many small documentation improvements
- feat: Add support for pseudo-encoding `LastRec`
- feat: Add support for _Extended QEMU Key Events`
# Pending
- feat: Add support for IPv6 addresses

**Comment by Kochise** [comment]
Thank you !

Beware, ensure to increase the release version :

https://github.com/sibson/vncdotool/blob/main/vncdotool/__init__.py

Especially when you'll update the Pypi package :

https://pypi.org/project/vncdotool/

**Comment by sibson** [comment]
1.1.0 released
