### ISSUE TITLE
Forced stdout breaks remote sessions

### ISSUE THREAD

**Issue by pevogam** [sibson/vncdotool#211]
Hi @sibson,

Is there any reason why [two functions](https://github.com/sibson/vncdotool/blob/17e66252fa7a72eccef8cc9b837543aed30524f0/vncdotool/client.py#L390) in the client module output explicitly to stdout instead of using the provided loggers? Some of our remote sessions break down because of some of this output and there isn't any easy way to prevent the output from being emitted. We already make full use of the logging levels and filters but the following code doesn't seem to respect that.

Any feedback is appreciated.

**Comment by sibson** [comment]
provided the default ./vncdo logging configuration prints the strings, I
don't see a reason not to change it to be.a proper logger.  I'll merge a
PR, but don't have time to make the change myself.

**Comment by pevogam** [comment]
No worries, I will push a PR. Thanks for the quick response!

**Comment by pevogam** [comment]
Pushed #213.
