### ISSUE TITLE
How to press "window" key | How open cmd.exe?

### ISSUE THREAD

**Issue by dmitrymaslov99** [sibson/vncdotool#212]
How click KeyPress - "Windows" key.
https://vncdotool.readthedocs.io/en/0.8.0/_modules/vncdotool/client.html
![image](https://user-images.githubusercontent.com/36110676/150689626-5ffa581a-e92a-45e2-92b8-f8659fdb28c3.png)

For example - open cmd.exe "win-r"

**Comment by cgb** [comment]
Windows key is commonly referred to as 'super'

So the way to send win-r is:
```
key super-r
```

**Comment by sibson** [comment]
We could add a winkey alias too.  I'd forgotten super is the winkey myself.
