### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [sibson/vncdotool#218]
Could you please consider to use unittest.mock instead of mock as a fallback?

https://trello.com/c/S6eADbii/64-remove-python-mock
https://fedoraproject.org/wiki/Changes/DeprecatePythonMock

**Comment by sibson** [comment]
I don't see a problem in doing so.  Not sure when I'll have time to make a PR and test.

**Comment by pgajdos** [comment]
In https://build.opensuse.org/package/show/devel:languages:python/python-vncdotool
you see that
https://build.opensuse.org/package/view_file/devel:languages:python/python-vncdotool/python-vncdotool-no-mock.patch
is enough down to at least python 3.6.
By the way, we have also
https://build.opensuse.org/package/view_file/devel:languages:python/python-vncdotool/remove-nose.patch
to remove usage of unmaintained nose. I would do a PR, however I am not sure about the infractructure files and CI, unfortunately.

**Comment by pmhahn** [comment]
The reference to the external `mock` has been replaced by `unittest.mock` with 029948a, which should be included with the next releasee.

**Comment by pgajdos** [comment]
Thanks!
