### ISSUE TITLE
Request: add a command "InputFile"  to input the whole file content

### ISSUE THREAD

**Issue by Neilpang** [sibson/vncdotool#220]
The `type` command can input simple string.
Sometimes, I need to input a complex  script as a string,  it's hard to escape the chars in the string.
So, it would be good to have a new command `InputFile`  or `typeFile` to  read the file content and type it in one by one.

thanks

**Comment by sibson** [comment]
https://github.com/sibson/vncdotool/blob/main/vncdotool/command.py#L93

**Comment by Neilpang** [comment]
thanks
