### ISSUE TITLE
Cannot connect to macOS

### ISSUE THREAD

**Issue by yushih** [sibson/vncdotool#230]
-  VNC server and version
 MacOS Ventura 13.1 builtin "Screen Sharing", configurated to use password authentication (https://support.apple.com/en-sg/guide/remote-desktop/apdbed09830/mac)

 - vncdotool version
 1.0.0 from pip install

 -  steps to reproduce
 Run `vncdotool -s <IP of Mac> -v type <str>`
I get:
```
INFO:root:connecting to 169.254.108.225:5900
INFO:twisted:Starting factory <vncdotool.command.VNCDoCLIFactory object at 0x7f9084dc2bf0>
INFO:twisted:Protocol version 3.889 not supported
INFO:twisted:Using protocol version 3.800
VNC password:
INFO:twisted:unknown auth response (16777216)
INFO:twisted:unknown auth response (39)
INFO:twisted:unknown auth response (1098216552)
INFO:twisted:unknown auth response (1701737577)
INFO:twisted:unknown auth response (1667331177)
INFO:twisted:unknown auth response (1869488239)
INFO:twisted:unknown auth response (1914724725)
INFO:twisted:unknown auth response (1953001330)
INFO:twisted:unknown auth response (1769628020)
INFO:twisted:unknown auth response (1768910368)
INFO:twisted:unknown auth response (1717660012)
INFO:twisted:unknown auth response (1970431232)
```
Thanks!

**Comment by sibson** [comment]
I don't have a Ventura MAC to test with.  There have been some updates recently that are yet to be released.   Would you be able to test with the latest code from main?

**Comment by pmhahn** [comment]
> vncdotool version1.0.0
…
> INFO:twisted:Protocol version 3.889 not supported

Version `v1.0.0` from PyPI is way to old; Support for _Apple Remote Desktop_ (ARD)  was added via b659053993b86ce6fb19d8042edf2f70d8f40c9e ,which is currently available only from git.

You can test that version by using this command:
```sh
pip install git+https://github.com/sibson/vncdotool.git@main
```

I don't have access to any macOS system so I cannot test it myself, but I'm closing this issue anyway. If the problem persists please feel free to re-open this issue or to create a new one.
