### ISSUE TITLE
fail to import module with error: segmentfault 

### ISSUE THREAD

**Issue by etaixiee** [sibson/vncdotool#277]
version:1.2.0
only can run when i replace [PyCryptodome](https://pypi.org/project/pycryptodome/) with [Crypto](https://pypi.org/project/crypto/) in [rfb.py](vncdotool/rfb.py):

```pythonn
from Crypto.Cipher import AES, DES
from Crypto.Hash import MD5
from Crypto.Util.number import bytes_to_long, long_to_bytes
```

**Comment by pmhahn** [comment]
Thank you for your report, but:
1. please at least provide some platform information, e.g. which version of Python you're using, on wich operating system, …
2. No program should ever segfault and if VNCdotool does by just using some other module, to me it looks like your system is broken somewhere and VNCdotool is just the messenger, and not the offender itself. Even is VNCdotool would switch to Crypto any other program using PyCryptodome on your system might still crash and would need to switch too. So lease check and fix your system.
3. Crypto is unmaintained and PyCrytodome is the modern replacement for it; quoting from PyPI:
> PyCryptodome is a fork of PyCrypto. It brings several enhancements with respect to the last official version of PyCrypto (2.6.1), for instance:

As this is no bug in VNCdotool I'm closing your issue.
