### ISSUE TITLE
How to operate the mouse scroll wheel

### ISSUE THREAD

**Issue by AppleHuang** [sibson/vncdotool#279]
How to operate the mouse wheel? Can you provide a specific code example? Thank you.

**Comment by pmhahn** [comment]
Most of the times the mouse wheel maps to button 4 and 5, so you have to repeatedly use `vncdotool click 4` and `vncdotool click 5` to simulate one notch of the wheel:
```console
$ vncdo --help
…
  click BUTTON          send a mouse BUTTON click
```
