### ISSUE TITLE
1.2.0 release build is missing

### ISSUE THREAD

**Issue by Neustradamus** [sibson/vncdotool#280]
Dear @sibson,

There is not the 1.2.0 release build, it is normal?
- https://github.com/sibson/vncdotool/releases
- https://github.com/sibson/vncdotool/tags

Thanks in advance.

**Comment by sibson** [comment]
thanks for pointing out.  pypi is the authoritative source and github releases aren't automated so I forgot.  I've created one now but not sure I will continue doing so in future.

**Comment by Neustradamus** [comment]
@sibson: In this case, you can remove all releases from here (and keep only tags):
- https://github.com/sibson/vncdotool/releases
