### ISSUE TITLE
Password protection check

### ISSUE THREAD

**Issue by Tri0L** [sibson/vncdotool#36]
Tell me please, how i can check a vnc password protection from Python script?

**Comment by sibson** [comment]
I don't think there is a good way currently, would need to rework the way passwords are requested.  Maybe it should just raise an Exception rather than prompting for a password.  Probably the quickest would be if you subclassed the VNCDoToolClient and overrode vncRequestPassword()

**Comment by sibson** [comment]
I've had a look at the code and I think you're best bet is to override vncRequestPassword() to either raise an exception or do something else meaningful in your script.  I don't think there is a change I can make to  simplify things further.
