### ISSUE TITLE
Colours swapped on VMWare

### ISSUE THREAD

**Issue by sibson** [sibson/vncdotool#42]
I'm running vncdo on a Linux client, and capturing images from a remote host, and it looks like a pixel encoding is being missed/ignored somewhere, with the result being that the captured image has the Red and Blue channels swapped.  Looks like a RGB vs BGR issue:

vncdo is expecting RGB but it looks like we're getting BGR.  A similar issue, https://github.com/kanaka/noVNC/issues/70

This is the code the needs to be investigated.
https://github.com/sibson/vncdotool/blob/master/vncdotool/client.py#L346
https://github.com/sibson/vncdotool/blob/master/vncdotool/client.py#L369

**Comment by sibson** [comment]
ServerInit contains format info, are we overwriting it? Is VMWare ignoring our setPixelFormat? 

https://github.com/sibson/vncdotool/blob/master/vncdotool/rfb.py#L196

**Comment by bobturbos** [comment]
The capture with the ESXi VNC server worked fine for me with this small modification to your code
 (BGRX instead of RGBX on L369)
https://github.com/sibson/vncdotool/pull/43/files

**Comment by agfor** [comment]
I ran into this issue with VMWare Fusion 8.

**Comment by sibson** [comment]
Likely fixed by https://github.com/sibson/vncdotool/pull/122, please re-open if that isn't the case
