### ISSUE TITLE
Can not connect to vnclog server

### ISSUE THREAD

**Issue by brantxiong** [sibson/vncdotool#44]
I started vnclog, and use vncviewer to connect to the vnclog server. But the vncviewer promots with password, what the password is? if I leave it blank or try the real server password, it all fails, showing connecting...  The vncviewer log is as following 
```
INFO:twisted:VNCLoggingServerFactory starting on 5902
INFO:twisted:Starting factory <vncdotool.loggingproxy.VNCLoggingServerFactory instance at 0x1044ad560>
INFO:proxy:new connection from 127.0.0.1
INFO:twisted:Starting factory <vncdotool.loggingproxy.VNCLoggingClientFactory instance at 0x1044b1f38>

```

**Comment by sibson** [comment]
The password is the same one used for the upstream vncserver.  Are you able to connect directly to upstream vncserver with your vncviewer?

**Comment by brantxiong** [comment]
yes, and I have tried the upstream vncserver password, stil fails, showing connecting..
