### ISSUE TITLE
Takes 30 seconds to run vncdo using Cygwin Python

### ISSUE THREAD

**Issue by nitrocode** [sibson/vncdotool#46]
Not sure why, but it takes me 30 seconds to send a string using "type" or "key" using python and vncdo on top of Cygwin on Windows 7 32bit. 

Cygwin 32 bit install
Install python/pip
pip install vncdotool

`vncdo -s 1.1.1.1::5999 type "root"`

The same command works almost instantly with Windows python and vncdotool installed by Windows pip. If I use a vdo file using the cygwin vncdotool, it will still take 30 seconds to initialize and then it will continue the vdo file with normal pauses. 

`vncdo -s 1.1.1.1::5999 ns.vdo`

Any idea why vncdo takes so long to initialize in Cygwin?

**Comment by sibson** [comment]
Running with -vvv to increase debugging output might offer some clues.  Its not something I'm able to investigate myself.

**Comment by sibson** [comment]
If you are still experiencing issues, please reopen the issue and provide additional details to help debug further.
