### ISSUE TITLE
Feature request: typeenter

### ISSUE THREAD

**Issue by nitrocode** [sibson/vncdotool#47]
It would be nice if vncdo could type and then hit enter on the same line without having to type the string and then key enter.

Maybe something like this?

`vncdo -s 1.1.1.1::5999 typeenter root`
`vncdo -s 1.1.1.1::5999 typeenter password`

This would save many lines of vncdo runs. 

...etc..etc

**Comment by sibson** [comment]
I think the following should work

```vncdo type root key enter```

http://vncdotool.readthedocs.org/en/latest/usage.html#basic-usage

**Comment by nitrocode** [comment]
Oh sweeet! I didn't even realize you could do that. :+1:
