### ISSUE TITLE
Is there a way to consolidate key ups and key downs using vnclog?

### ISSUE THREAD

**Issue by nitrocode** [sibson/vncdotool#48]
Just wondering if there is a switch or an easy way to consolidate something like this:

    keydown a
    keyup a
    keydown b
    keyup b
    keydown c
    keyup c

to

    type "abc"

**Comment by sibson** [comment]
is type abc not working for you?

**Comment by nitrocode** [comment]
I mean with vnclog. If you use vnclog to key log your VNC session and you login to your ubuntu server using user "root" and then enter, this will create a keyup and keydown command for each button making it 10 statements. Whereas if you manually write the command, it will take only one or two statements.

`type "root"`
`key enter`

or 

`type "root" key enter`

Just thought it would be a nice feature request.

**Comment by sibson** [comment]
yes, a script optimizer would be a nice feature.  The mouse move commands are especially verbose.  It could easily be standalone command that could run against any captured file.

**Comment by nitrocode** [comment]
I like the way you think. Here's a quick script:

https://github.com/nitrocode/cleanvdo/blob/master/convdo.py

It's incomplete, the switches aren't in place, but it rounds pauses, removes move/click, if bsp is found it removes bsp and the key before it, it also removes keyup's, and replaces keydown's with just key.

./convdo somefile.vdo > short.vdo

I have it removing the move/click because I'm doing strictly linux terminal stuff, feel free to modify or add to it. :)

**Comment by sibson** [comment]
looks promising

**Comment by nitrocode** [comment]
Finally had some time and made some progress. Decreased one of my files from 1200 lines to 78! Thanks again for this tool. It's made ova automation and configuration a breeze.
