### ISSUE TITLE
Mouse pointer on Windows XP

### ISSUE THREAD

**Issue by pevogam** [sibson/vncdotool#51]
Hi,

Have you experienced problems with the mouse pointer on Windows (in particular XP, haven't tested newer versions yet)? In particular I did two tests, one which explained one problem and one which I still can't explain.

The first discovery is that the mouse pointer is initialized at (0,0) which are the vnc-believed coordinates while in reality the mouse might be in any location (x,y)) e.g. when connecting to already active screen. The result from this is that if I move to point (10,10) this will rather result in the mouse pointer moving to (x+10,y+10) instead of the desired (0+10,0+10). A current workaround I have is:

[PSEUDOCODE]
mouse_move(screen_width, screen_height) # since the mouse cannot move beyond the screen
mouse_move(0, 0) # now the actual (0, 0)

The second problem is more mysterious. It seems that the mouse doesn't move in deterministic way. After resetting it like above and performing test where the mouse is moved to (0, 0) and then to (100, 100) where it is also clicked (this repeated a few thousand times), it seems that it moved to at least a few different positions (see first screenshot). After doing a grid of clicks like this

[PSEUDOCODE]
for i in range(5,40):
    for j in range(5,40):
        g.click(10\*i, 10\*j)

I obtain the second screenshot (first column is correct, then everything displaced.

![monte carlo](https://cloud.githubusercontent.com/assets/1969979/10265110/c69bb06a-6a22-11e5-84d2-faed6e3cdd81.png)
![grid test](https://cloud.githubusercontent.com/assets/1969979/10265111/c69fcb5a-6a22-11e5-8720-07ae532cd573.png)

I hope this is informative and perhaps you have seen any of it before.

**Comment by sibson** [comment]
Unfortunately, I don't have access to a windows machine.  

In the first case, mouseMove, is suppose to be absolute but it sounds like its behaving relatively.  Do you have you VM/VNC server configured to use a mouse rather than a tablet as the input device?

I wonder if the second issue is another symptom of relative vs absolute.

**Comment by pevogam** [comment]
Yes, Qemu uses the default option for 1.5.3 which at least according to what I read is a ps/2 mouse. Should I try with the tablet option?

Here is a sample of the Qemu configuration which also includes the vnc server:

/usr/libexec/qemu-kvm \
    -S  \
    -name 'vm5' \
    -M pc  \
    -nodefaults  \
    -vga std  \
    -chardev socket,id=hmp_id_hmp1,path=/tmp/monitor-hmp1-20150812-010745-qf4xtciM,server,nowait \
    -mon chardev=hmp_id_hmp1,mode=readline  \
    -chardev socket,id=serial_id_serial1,path=/tmp/serial-serial1-20150812-010745-qf4xtciM,server,nowait \
    -device isa-serial,chardev=serial_id_serial1  \
    -chardev socket,id=seabioslog_id_20150812-010745-qf4xtciM,path=/tmp/seabios-20150812-010745-qf4xtciM,server,nowait \
    -device isa-debugcon,chardev=seabioslog_id_20150812-010745-qf4xtciM,iobase=0x402 \
    -device piix3-usb-uhci,id=isdnhub,bus=pci.0,addr=03 \
    -drive id=drive_image1,if=none,cache=none,file=/mnt/local/images/vm5/winxp-sp3-32_vm5.qcow2 \
    -device ide-hd,id=image1,drive=drive_image1,bus=ide.0,unit=0 \
    -device rtl8139,mac=02:00:00:00:20:13,id=idYxotbk,netdev=id82MCVL,bus=pci.0,addr=04  \
    -netdev tap,id=id82MCVL,fd=37 \
    -device rtl8139,mac=02:00:00:00:20:14,id=idta6jxQ,netdev=idLGKXLX,bus=pci.0,addr=05  \
    -netdev tap,id=idLGKXLX,fd=39 \
    -device rtl8139,mac=02:00:00:00:20:15,id=idXpguHf,netdev=idjtTHNj,bus=pci.0,addr=06  \
    -netdev tap,id=idjtTHNj,fd=61  \
    -m 1024  \
    -smp 2,maxcpus=2,cores=1,threads=1,sockets=2  \
    -cpu 'SandyBridge' \
    -drive media=cdrom,file=/mnt/local/isos/winutils.iso,bus=0,unit=1  \
    -vnc :3  \
    -rtc base=2014-07-15,clock=vm,driftfix=none  \
    -boot order=cdn,once=dcn,menu=off \
    -enable-kvm

**Comment by sibson** [comment]
I think tablet is worth a try.

**Comment by pevogam** [comment]
Unfortunately not many things changed. One could definitely notice some rescaling though:

![grid test tablet](https://cloud.githubusercontent.com/assets/1969979/10566604/27fded9e-75ec-11e5-958b-cb50bce5a976.png)
![monte carlo tablet](https://cloud.githubusercontent.com/assets/1969979/10566605/280f33d8-75ec-11e5-92d6-0480df10a025.png)

(You can compare these shots with the ones above)

**Comment by pevogam** [comment]
Hi Marc,

So I spent more time investigating this issue and have some interesting results. The results are generated from the grid test above with grid step h=10 pixels and the hit test above with hit number n=100. Here more details:

- The grid test measures if the mouse clicks (respectively presses and releases the button) correctly on a grid of location points.

- The hit test measures if the mouse clicks at a fixed point by hovering at another point first. Here, it was extended so that the mouse first moves to a random point within a range and then goes back and clicks at the fixed point. If in the end of the test, there is only the point (namely the fixed point), the test was passed. As you will see this is not the case in at least a few cases.

Here is a sample code to describe the different variants of mouse clicking and mouse moving I have used to obtain the different outcomes:

**c=0.0** -> no click timeout and not fixed (default clicking in vncdotool)
```python
client.mousePress(LEFT_BUTTON)
```

**c=0.0 f=0.0** -> no click timeout and fixed (by adding extra "mouseUp" line of code)
```python
client.mousePress(LEFT_BUTTON)
client.mouseUp(LEFT_BUTTON)
```

**c=0.1** -> 0.1 click timeout and not fixed
```python
client.mousePress(LEFT_BUTTON)`
time.sleep(0.1)
```

**c=0.1 f=0.0** -> 0.1 click timeout before fix
```python
client.mousePress(LEFT_BUTTON)
time.sleep(0.1)
client.mouseUp(LEFT_BUTTON)
```

**c=0.0 f=0.1** -> 0.1 click timeout after fix
```python
client.mousePress(LEFT_BUTTON)
client.mouseUp(LEFT_BUTTON)
time.sleep(0.1)
```

**c=0.1 f=0.1** -> 0.1 click timeouts before and after the fix
```python
client.mousePress(LEFT_BUTTON)
time.sleep(0.1)
client.mouseUp(LEFT_BUTTON)
time.sleep(0.1)
```

For the function calls for mouse_move I tested the following cases:

**m=30** -> move step of 30 pixels
```python
client.mouseDrag(location.get_x(), location.get_y(), step=30)
```

**m=0** -> instant move (no dragging)
```python
client.mouseMove(location.get_x(), location.get_y())
```

And here are the canvas results from the two tests:

- Grid test results for all variants:
![grid_test](https://cloud.githubusercontent.com/assets/1969979/14468657/f267ae24-00e0-11e6-81e9-ded3c0c88507.jpg)

- Hit test results for all variants:
![hit_test](https://cloud.githubusercontent.com/assets/1969979/14468666/f8e69238-00e0-11e6-8a0e-1550ee2a42f6.jpg)

I can possibly draw some interesting conclusions from these results. Here are mine:

**c=0.0** --> The vncdotool with no modifications on my side fails to release the mouse in the case of instant mouse move m=0 resulting in trails in both the grid and the random initial points. However, the case of mouse drag with m=30 handles this better, revealing a race condition of some kind (possibly delay in the mouse release).

**c=0.0 f=0.0** --> Simply adding the fix I suggested before reduces the amount of mouse trailing for m=0. Until now, I have used the fix with m=30 which seems to have solved the problem as you can also see in the tests. However, adding more load to the testing, e.g. running the hit test with 2000 hit trials finally showed (in red) that the fix only is not a solution. This means that in general, testing with m=0 reveals better the race conditions that arise and the errors with m=30 might be almost undetectable but still existent (leading to failed clicks and failed automation usage).

**c=0.1** --> Adding timeout after the mouse press without the fix makes no difference with c=0.0.

**c=0.1 f=0.0**  --> This seems to be the solution of the race condition. It performed perfectly in all variant (including the more revealing m=0) and later on didn't show any errors on n=2000 and h=2 cases of the hit and grid tests.

**c=0.0 f=0.1** --> The extra timeout after the fixed helped further reduce the frequency of failures but still shows some percentage of errors.

**c=0.1 f=0.1** --> Adding both timeouts works as well as c=0.1 f=0.0 but it seems that the second timeout doesn't contribute as much so this fix might be an overkill.

Overall, the error might as well be on the server side of Qemu but at least it is worth to document this workaround (namely the click fixes of "c=0.1 f=0.0") if other people using Qemu experience this problems. I hope you find this information useful. Feel free to close this issue.

**Comment by sibson** [comment]
First thanks for taking the time to do a thorough analysis. I've not fully digested this but I've two ideas.  First I wonder if the server is coalescing pointerEvents() received during a tick and thus "losing" events.  The second being could vncdo be mishandling cursor position.  If you want to try it out its [here](https://github.com/sibson/vncdotool/tree/cursor-cleanup), as I'm not setup to test it properly at the moment.

**Comment by pevogam** [comment]
Here are results from the *cursor-cleanup* branch for m=0 and m=30. This is only the code in the branch, none of the fixes above applied, i.e. the **c=0.0** case.

- Results from the grid test with **c=0.0 m=0**:

![grid_test_windows_branch](https://cloud.githubusercontent.com/assets/1969979/14492217/2d4b85fe-017e-11e6-88a0-cff7e943cd85.png)

- Results from the hit test with **c=0.0 m=0**:

![hit_test_windows_branch](https://cloud.githubusercontent.com/assets/1969979/14492226/3df825a6-017e-11e6-8060-d4ceb01b1904.png)

- Results from the grid test with **c=0.0 m=30**:

![hit_test_windows_branch_m30](https://cloud.githubusercontent.com/assets/1969979/14492261/7cfb2ac8-017e-11e6-9f08-1faa2e3b7884.png)

- Results from the hit test with **c=0.0 m=30**:

![hit_test_windows_branch_m30](https://cloud.githubusercontent.com/assets/1969979/14492393/34f80074-017f-11e6-9e7c-3238481f5a8b.png)

You can take your time if you would still prefer to find a fix for this. Overall, I could say there is an improvement with the previous **c=0.0** cases.

**Comment by sibson** [comment]
If you are still experiencing issues, please reopen the issue and provide additional details to help debug further.
