### ISSUE TITLE
Shared vnc connections

### ISSUE THREAD

**Issue by pevogam** [sibson/vncdotool#52]
Hi Marc,

Does the vncdotool client support shared vnc connections, i.e. passing the "shared" flag to a vnc server? It seems that the only arguments we can pass during connection setup are "server" and "password".

**Comment by sibson** [comment]
It uses shared by default, https://github.com/sibson/vncdotool/blob/master/vncdotool/client.py#L420

**Comment by pevogam** [comment]
You are absolutely right, sorry to miss that :)

**Comment by sibson** [comment]
it was a reasonable question, as many clients default to exclusive mode.
