### ISSUE TITLE
Asynchroneous MouseDrag

### ISSUE THREAD

**Issue by pevogam** [sibson/vncdotool#53]
Hi Marc,

I have a strange problem occurring when using MouseDrag. I recompiled a more verbose version of Qemu and as you can see below, it prints the mouse positions on the vnc server. What is particularly interesting about the output below is that there is a race condition - the vncdotool client fires up a set of mouse move instructions (the implementation of MouseDrag) but continues with the later instructions before the server has actually moved to the desired position. As in this case, a later operation is click, the client clicks on a position along the trajectory of the delayed mouse move. The "client" lines come from the vncdotool client while the "aexpect" ones come from the vnc server.

Do you have any clue on why this happens with the simple synchronous use case?

11/28 12:46:27 DEBUG|    region:0228| Looking for image win7-start-button
11/28 12:46:27 DEBUG|    client:0234| captureRegion /tmp/guibendermh0tZu.png
11/28 12:46:27 DEBUG|    client:0244| captureSave /tmp/guibendermh0tZu.png
11/28 12:46:27 DEBUG|imagefinde:0135| Performing opencv-ccoeff_normed multiple template matching with color
11/28 12:46:27 DEBUG|imagefinde:0155| Best match with value 0.763526976109 (similarity 0.7) and location (x,y) (6, 730)
11/28 12:46:27 DEBUG|imagefinde:0165| Best match is accetable
11/28 12:46:27 DEBUG|    client:0312| mouseDrag 27,749
11/28 12:46:28 DEBUG|    client:0304| mouseMove 0,0
11/28 12:46:28 DEBUG|    client:0304| mouseMove 0,30
11/28 12:46:28 DEBUG|    client:0304| mouseMove 0,60
11/28 12:46:28 DEBUG|    client:0304| mouseMove 0,90
11/28 12:46:28 DEBUG|    client:0304| mouseMove 0,120
11/28 12:46:29 DEBUG|    client:0304| mouseMove 0,150
11/28 12:46:29 DEBUG|    client:0304| mouseMove 0,180
11/28 12:46:29 DEBUG|    client:0304| mouseMove 0,210
11/28 12:46:29 DEBUG|    client:0304| mouseMove 0,240
11/28 12:46:29 DEBUG|    client:0304| mouseMove 0,270
11/28 12:46:30 DEBUG|    client:0304| mouseMove 0,300
11/28 12:46:30 DEBUG|    client:0304| mouseMove 0,330
11/28 12:46:30 DEBUG|    client:0304| mouseMove 0,360
11/28 12:46:30 DEBUG|    client:0304| mouseMove 0,390
11/28 12:46:30 DEBUG|    client:0304| mouseMove 0,420
11/28 12:46:31 DEBUG|    client:0304| mouseMove 0,450
11/28 12:46:31 DEBUG|    client:0304| mouseMove 0,480
11/28 12:46:31 DEBUG|    client:0304| mouseMove 0,510
11/28 12:46:31 DEBUG|    client:0304| mouseMove 0,540
11/28 12:46:31 DEBUG|    client:0304| mouseMove 0,570
11/28 12:46:32 DEBUG|    client:0304| mouseMove 0,600
11/28 12:46:32 DEBUG|    client:0304| mouseMove 0,630
11/28 12:46:32 DEBUG|    client:0304| mouseMove 0,660
11/28 12:46:32 DEBUG|    client:0304| mouseMove 0,690
11/28 12:46:32 DEBUG|    client:0304| mouseMove 0,720
11/28 12:46:33 DEBUG|    client:0304| mouseMove 0,720
11/28 12:46:33 DEBUG|    client:0304| mouseMove 27,749
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 0)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 30)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 60)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 90)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 120)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 150)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 180)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 210)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 240)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 270)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 300)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 330)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 360)
11/28 12:46:33 INFO |    region:0407| Clicking at win7-start-button
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 390)
11/28 12:46:33 DEBUG|    client:0194| mousePress 1
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 420)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 450)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 480)
11/28 12:46:33 DEBUG|    client:0219| mouseUp 1
11/28 12:46:33 INFO |    region:0330| Waiting for win7-start-admin
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 510)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 540)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 570)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 600)
11/28 12:46:33 DEBUG|    region:0228| Looking for image win7-start-admin
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 630)
11/28 12:46:33 DEBUG|    client:0234| captureRegion /tmp/guibenderYqInsj.png
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 660)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 690)
11/28 12:46:33 DEBUG|    client:0244| captureSave /tmp/guibenderYqInsj.png
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 720)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (0, 720)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (27, 749)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (27, 749)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (27, 749)
11/28 12:46:33 INFO |   aexpect:0923| [qemu output] P: (x, y): (27, 749)
11/28 12:46:33 DEBUG|imagefinde:0135| Performing opencv-ccoeff_normed multiple template matching with color
11/28 12:46:33 DEBUG|imagefinde:0155| Best match with value 0.310983777046 (similarity 0.8) and location (x,y) (530, 63)
11/28 12:46:33 DEBUG|imagefinde:0162| Best match is not accetable

**Comment by sibson** [comment]
vncdotool makes no synchronous guarantees and is async by default.  It doesn't wait for the server to move the mouse before sending the next event.  From the log it looks like vncdotool completed the Drag operation before sending the click.  

I may be misreading the output but I don't see qemu recording the click.  Ideally, a server would process all move events before a click event but I don't *know* if that happens.  Also, depending how you created that log, stdout buffering could be effecting the ordering of the log messages.  

Using ```expect someimage.png``` is the best way to ensure there is a barrier between the drag and click events.  Alternatively, you can use pause X to give the server time to catch up but that can be fragile.

hope that helps

**Comment by pevogam** [comment]
The event of Qemu recording the click wasn't enabled which is the reason why it is not visible in the log. After doing some more testing, it seems that this is rather a property of the logging which appears only with relative mouse coordinates. Ultimately, I just wanted to make sure that such race condition is possible even though not expected and/or desired.

Topic closed on my side.
