### ISSUE TITLE
ESXi VNC only capturing top part of screen

### ISSUE THREAD

**Issue by kschillz** [sibson/vncdotool#55]
I'm connecting to an ESXi vm console with vncdotool and the captureScreen function is only grabbing the top part of the screen, like so:
![img](https://cloud.githubusercontent.com/assets/857442/11939372/b1196146-a7ef-11e5-8faa-e5a9b7727dec.png)

I've been trying to debug and it looks like the VNC screen size is correct because I can send clicks below the captured image. The updateRectangle function in client.py mentions that the ESXi screen is sent in chunks but its not receiving enough chunks to make up the entire image.

I'll do my best to get more information if needed.

**Comment by sibson** [comment]
thanks for the info, unfortunately I don't have access to an ESXi server nor much free time to debug myself. Mouse clicks and screen capture are pretty isolated so I don't think mouse clicks are a reliable indicator.  

I'd suggest instrumenting [here](https://github.com/sibson/vncdotool/blob/master/vncdotool/client.py#L363) to see what self.screen.size is and what updates are being received.  [This](https://github.com/sibson/vncdotool/blob/master/vncdotool/client.py#L378) looks prone to an order of ops issue. Say, the bottom half was sent first then the top half would clobber it.

**Comment by rzk** [comment]
ESXi wants rfb.HEXTILE_ENCODING, while you default to rfb.RAW_ENCODING.

You should probably add ESXi flavor option to vncdotool since we have now two things broken with ESXi: colors and encoding.

**Comment by lucastho** [comment]
I worked on this a little bit, but was not able to come up with a good solution. It seems that vmware's VNC server doesn't transmit an entire screen update when it receives a FramebufferUpdateRequest command as it should. Instead, it only transmits the first 1 or 2 rows of the rectangles.
![vmwarescreen](https://cloud.githubusercontent.com/assets/12203734/18768669/c466b314-80db-11e6-9fd5-08518e9ad1f9.png)


Switching it to HEXTILE (by editing client.py) made the captured screen area larger, so it was 2 rows of rectangles instead of 1 row. 

As a side note, the perl Net::VNC implementation has exactly the same compatibility problem.

**Comment by rzk** [comment]
> Also, it seems that the resolution plays a role. 640x480 resolution seems to always get the whole screen.

Not sure here.
I'm capturing 800x600 screenshots from ESXi 5. Target system is Linux with vmwgfx drm loaded.

**Comment by sibson** [comment]
I'm curious if https://github.com/sibson/vncdotool/pull/87 has helped fix this issue.  If someone could test and report back that would be helpful.

**Comment by lucastho** [comment]
Thanks for the update.
 
I've re-tested against the same ESX with this, and the behavior seems identical. If it's helpful I could share a packet capture.

**Comment by rebasegod** [comment]
#87 Will only change anything, if:
1.) ESXi supports the "DesktopSIze Pseudo-Encoding". I would strongly assume it does.
2.) Your client tells the server that it supports the "DesktopSIze Pseudo-Encoding". This can be done in your application, in the class that inherits from `VNCDoToolClient`. In my application I added this to my `vncConnectionMade()` method: `self.setEncodings([RAW_ENCODING, PSEUDO_DESKTOP_SIZE_ENCODING])`. The encoding constants are defined in `vncdotool.rfb`, so import them as well.

Hope this helps :)

**Comment by bursant** [comment]
Hey guys,

just a quick workaround for this tested on esxi 6.5. If you have VCenter, you can do screenshoot right away using get request:

https://1.2.3.5/screen?id=vm-162

1.2.3.5 would be VCenter address and vm-162 is moref of vm. You can get it for example via pyvmomi when you get vm details.

**Comment by sibson** [comment]
https://github.com/sibson/vncdotool/pull/126 and https://github.com/sibson/vncdotool/pull/122 may have solved this. Is anyone able to validate?

**Comment by sibson** [comment]
If you are still experiencing issues, please reopen the issue and provide additional details to help debug further.
