### ISSUE TITLE
Can't install  on rpi jessie

### ISSUE THREAD

**Issue by OdysLam** [sibson/vncdotool#68]
When I am trying to install it I get the following error 👍 

Command "/usr/bin/python -u -c "import setuptools, tokenize;**file**='/tmp/pip-build-Ktya7_/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(**file**).read().replace('\r\n', '\n'), **file**, 'exec'))" install --record /tmp/pip-smTj_t-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-Ktya7_/pillow/

**Comment by sibson** [comment]
Hi, this looks like a problem with [Pillow](https://python-pillow.org/) rather than vncdotool.  My guess is either the version in requirements.txt needs to be updated or you are using python 3.

**Comment by sibson** [comment]
If you are still experiencing issues, please reopen the issue and provide additional details to help debug further.
