### ISSUE TITLE
2 Desfunctional Errors on Ubuntu 16.04

### ISSUE THREAD

**Issue by qemu-buro-point-dpkg** [sibson/vncdotool#78]
Hi,
I am cycling around an "hello world" vncdotools, but there is no way.

## So first intent: tried to install it via github:
git clone https://github.com/sibson/vncdotool
cd vncdotool/
python3.5 setup.py install -record files.txt
vncdo -s localhost:0 type "hello world"
`Traceback (most recent call last):
  File "/usr/local/bin/vncdo", line 9, in <module>
    load_entry_point('vncdotool==0.10.1.dev0', 'console_scripts', 'vncdo')()
  File "/usr/local/lib/python3.5/dist-packages/vncdotool-0.10.1.dev0-py3.5.egg/vncdotool/command.py", line 381, in vncdo
  File "/usr/local/lib/python3.5/dist-packages/vncdotool-0.10.1.dev0-py3.5.egg/vncdotool/command.py", line 268, in setup_logging
`**TypeError: unorderable types: NoneType() > int()
**
## second intent: installed it via pip:
sudo -H pip install vncdotool
vncdo -s localhost:0 type "hello world"
Traceback (most recent call last):
  File "/usr/local/bin/vncdo", line 7, in <module>
    from vncdotool.command import vncdo
  File "/usr/local/lib/python3.5/dist-packages/vncdotool/command.py", line 79
    print data
             ^
**SyntaxError: Missing parentheses in call to 'print'**

## btw: the environment seems functional: gives a working jpg
x11vnc -display :0
vncsnapshot -quiet -allowblank -compresslevel 0 localhost:0 snapshot_${PRINTF_NR}.jpg

**Question**: How can I achieve such an hello world. Thanks in advance. As debian-qa jenkins uses your software, there must be a working version around, must not it?

**Comment by sibson** [comment]
python 3 support is a new feature in vncdotool.  I've not released a py3 compatible version to pypi so pip install will fail.   I suspect the github install is also a py3 related issue that needs to be fixed.

**Comment by OdysLam** [comment]
Although I did not run it, i have installed for python 3 via pip3 command

**Comment by qemu-buro-point-dpkg** [comment]
Thanks for the quick reply first. Anyway I wonder how prominent users as debian qa could keep on running vncdotools successfully in the meantime. So their might be successfully tested thus so to say stable versions around? - I should ask them?
Thanks in advance for a comment on this question, too.
